import { SITE_URL } from "~/content/site";
import type { Lang } from "~/i18n/ui";

// The privacy policy, in all three shipped locales. Paragraphs are HTML because
// the policy needs inline links and <code> for the exact storage keys — naming
// the key is the difference between a policy and a promise.

export interface PrivacyBlock {
	heading: string;
	level: 2 | 3;
	paragraphs: string[];
	/** Render the "change your answer" control after this block. */
	manage?: boolean;
}

export interface PrivacyCopy {
	title: string;
	description: string;
	eyebrow: string;
	intro: string;
	manageCta: string;
	blocks: PrivacyBlock[];
}

const MAILTO = '<a href="mailto:founder@getbrainstorm.online">founder@getbrainstorm.online</a>';
const GITHUB = '<a href="https://github.com/brainstorm-os" rel="noopener noreferrer">GitHub</a>';
const repo = (label: string) =>
	`<a href="https://github.com/brainstorm-os/site" rel="noopener noreferrer">${label}</a>`;
const SITE_LINK = `<a href="${SITE_URL}">${SITE_URL}</a>`;

const privacy: Record<Lang, PrivacyCopy> = {
	en: {
		title: "Privacy policy",
		description: "What this site stores, when it starts, and how to change your mind.",
		eyebrow: "Legal",
		manageCta: "Change your answer",
		intro: `Brainstorm is a local-first product, and this site follows the same posture: collect as little as possible, keep what is collected boring, ask before storing anything, and never trade your attention or your data. This page describes everything the site at ${SITE_LINK} does with data. The Brainstorm app itself stores your data on your machine and has no account system; nothing on this page is about the app.`,
		blocks: [
			{ heading: "What we collect", level: 2, paragraphs: [] },
			{
				heading: "Usage analytics — only if you say yes",
				level: 3,
				manage: true,
				paragraphs: [
					"We would like to count visits and see which pages get read. We use Amplitude for that, on its EU servers, and it runs only if you answer yes to the question at the bottom of the page. Until you do, the analytics code is never downloaded, never runs, and writes nothing to your device — the choice is opt-in, not a switch on something already loaded.",
					'If you say yes, two things are stored on your device, in <code>localStorage</code> rather than in cookies. First, a random device id and session id generated by Amplitude: they identify a browser, not a person, and are never joined to a name or an email. Second, our own record of your answer — the word "granted" or "denied" and the date you gave it — under the key <code>bs-consent</code>. If you say no, only the second one is stored, so we know not to ask again.',
					"What gets sent while it is on: the page you are on, its title and referrer, your browser's language and screen size, and named events for the things worth counting — a download click (which platform, which build) and a newsletter or waitlist signup. Amplitude derives an approximate country from your IP address. We never send your email address, your name, or anything you type into a field.",
					"The legal basis is your consent, under GDPR Art. 6(1)(a) and the ePrivacy rules that cover storing anything on your device. Amplitude Inc. acts as our processor under a data-processing agreement, with the data held in the EU. Event data is kept for 12 months and then deleted. Your answer is remembered for 12 months, after which we ask again.",
					'You can change your answer at any time — the "Privacy choices" link in the footer of every page reopens the question. Saying no there stops the tracking immediately and deletes the stored device id from your browser.',
					"If your browser sends a Global Privacy Control or Do Not Track signal, we take that as a no: the question is never shown, nothing is loaded, and nothing is stored.",
				],
			},
			{
				heading: "Your email address, if you give it to us",
				level: 3,
				paragraphs: [
					`If you join the waitlist or subscribe to product updates, we store the email address you submit in a database (hosted by Turso) and use it for exactly one thing: sending you Brainstorm product updates. We do not share it, sell it, or enrich it. To have it removed, email ${MAILTO} and we will delete it.`,
				],
			},
			{
				heading: "A theme preference",
				level: 3,
				paragraphs: [
					'If you switch between light and dark theme, the choice is stored in a <code>bs-theme</code> cookie so the site and the docs open in the theme you picked. It contains the word "light" or "dark" and nothing else. It is functional, not tracking, and it is set whether or not you consent to analytics.',
				],
			},
			{
				heading: "Server logs",
				level: 3,
				paragraphs: [
					"The site is hosted on Vercel, which keeps standard, short-lived request logs (IP address, user agent) for operations and abuse prevention, acting as our processor.",
				],
			},
			{
				heading: "What loads from third parties",
				level: 2,
				paragraphs: [
					"The product-tour video embeds from <code>youtube-nocookie.com</code> and only loads after you press play; until then no request goes to YouTube. The footer shows badges from launch directories we are listed on (VerifiedDR, Endors, KittyLaunch, ListBulb, Product Watch, StartupBase) — loading those images sends the standard request data (IP address, user agent) to those hosts, as with any image on the web. Apart from Amplitude, and only after you say yes, no third-party script runs on this site. Downloads are served from GitHub Releases.",
				],
			},
			{
				heading: "Your rights",
				level: 2,
				paragraphs: [
					`Under the GDPR and similar laws you can ask what we hold about you, ask for it to be corrected or deleted, object to processing, and withdraw consent as easily as you gave it. Withdrawal is the footer link described above and takes effect at once. For the waitlist, deletion is the whole story — your email address is the only personal data we hold. Write to ${MAILTO} or open an issue on ${GITHUB}.`,
				],
			},
			{
				heading: "Changes",
				level: 2,
				paragraphs: [
					`If this policy changes, the date above changes with it, and the history is public in the site's ${repo("source repository")}.`,
				],
			},
		],
	},
	de: {
		title: "Datenschutzerklärung",
		description: "Was diese Website speichert, ab wann, und wie du es wieder änderst.",
		eyebrow: "Rechtliches",
		manageCta: "Antwort ändern",
		intro: `Brainstorm ist ein lokal-first Produkt, und diese Website hält es genauso: so wenig wie möglich erheben, das Erhobene langweilig halten, vor dem Speichern fragen und weder deine Aufmerksamkeit noch deine Daten verkaufen. Diese Seite beschreibt alles, was die Website unter ${SITE_LINK} mit Daten tut. Die Brainstorm-App selbst speichert deine Daten auf deinem Rechner und hat kein Konto-System; nichts auf dieser Seite betrifft die App.`,
		blocks: [
			{ heading: "Was wir erheben", level: 2, paragraphs: [] },
			{
				heading: "Nutzungsstatistik — nur wenn du zustimmst",
				level: 3,
				manage: true,
				paragraphs: [
					"Wir würden gern Besuche zählen und sehen, welche Seiten gelesen werden. Dafür nutzen wir Amplitude auf dessen EU-Servern, und es läuft nur, wenn du die Frage am unteren Seitenrand mit Ja beantwortest. Bis dahin wird der Analyse-Code nie geladen, läuft nie und schreibt nichts auf dein Gerät — es ist ein Opt-in, kein Schalter an etwas bereits Geladenem.",
					'Wenn du zustimmst, werden zwei Dinge auf deinem Gerät gespeichert, in <code>localStorage</code> statt in Cookies. Erstens eine zufällige Geräte- und Sitzungskennung von Amplitude: Sie identifiziert einen Browser, keine Person, und wird nie mit einem Namen oder einer E-Mail-Adresse verknüpft. Zweitens unser eigener Vermerk über deine Antwort — das Wort "granted" oder "denied" und das Datum — unter dem Schlüssel <code>bs-consent</code>. Wenn du ablehnst, wird nur der zweite Eintrag gespeichert, damit wir nicht erneut fragen.',
					"Was gesendet wird, solange es an ist: die aufgerufene Seite mit Titel und Referrer, Sprache und Bildschirmgröße deines Browsers sowie benannte Ereignisse für das, was zählbar sein soll — ein Download-Klick (welche Plattform, welcher Build) und eine Newsletter- oder Warteliste-Anmeldung. Amplitude leitet aus deiner IP-Adresse ein ungefähres Land ab. Wir senden nie deine E-Mail-Adresse, deinen Namen oder etwas, das du in ein Feld tippst.",
					"Rechtsgrundlage ist deine Einwilligung nach Art. 6 Abs. 1 lit. a DSGVO sowie den ePrivacy-Regeln, die das Speichern auf deinem Gerät betreffen. Amplitude Inc. ist unser Auftragsverarbeiter mit Auftragsverarbeitungsvertrag, die Daten liegen in der EU. Ereignisdaten werden 12 Monate aufbewahrt und dann gelöscht. Deine Antwort merken wir uns 12 Monate, danach fragen wir erneut.",
					'Du kannst deine Antwort jederzeit ändern — der Link "Datenschutz-Optionen" im Fuß jeder Seite öffnet die Frage erneut. Ein Nein dort beendet die Erfassung sofort und löscht die gespeicherte Gerätekennung aus deinem Browser.',
					"Sendet dein Browser ein Global-Privacy-Control- oder Do-Not-Track-Signal, werten wir das als Nein: Die Frage erscheint nicht, es wird nichts geladen und nichts gespeichert.",
				],
			},
			{
				heading: "Deine E-Mail-Adresse, wenn du sie uns gibst",
				level: 3,
				paragraphs: [
					`Wenn du dich auf die Warteliste setzt oder Produkt-Updates abonnierst, speichern wir die übermittelte E-Mail-Adresse in einer Datenbank (gehostet von Turso) und nutzen sie für genau eines: dir Brainstorm-Produkt-Updates zu schicken. Wir geben sie nicht weiter, verkaufen sie nicht und reichern sie nicht an. Zum Löschen schreib an ${MAILTO}, und wir entfernen sie.`,
				],
			},
			{
				heading: "Eine Farbschema-Einstellung",
				level: 3,
				paragraphs: [
					'Wenn du zwischen hellem und dunklem Farbschema wechselst, wird die Wahl in einem <code>bs-theme</code>-Cookie gespeichert, damit Website und Doku im gewählten Schema öffnen. Es enthält das Wort "light" oder "dark" und sonst nichts. Es ist funktional, kein Tracking, und wird unabhängig von deiner Analyse-Entscheidung gesetzt.',
				],
			},
			{
				heading: "Server-Logs",
				level: 3,
				paragraphs: [
					"Die Website läuft bei Vercel, das übliche, kurzlebige Request-Logs (IP-Adresse, User-Agent) für Betrieb und Missbrauchsabwehr führt und dabei als unser Auftragsverarbeiter handelt.",
				],
			},
			{
				heading: "Was von Dritten geladen wird",
				level: 2,
				paragraphs: [
					"Das Produkt-Tour-Video ist von <code>youtube-nocookie.com</code> eingebettet und lädt erst, wenn du auf Play drückst; vorher geht keine Anfrage an YouTube. Der Fußbereich zeigt Badges von Launch-Verzeichnissen, in denen wir gelistet sind (VerifiedDR, Endors, KittyLaunch, ListBulb, Product Watch, StartupBase) — das Laden dieser Bilder sendet die üblichen Anfragedaten (IP-Adresse, User-Agent) an diese Hosts, wie bei jedem Bild im Web. Außer Amplitude, und auch das erst nach deinem Ja, läuft kein Skript Dritter auf dieser Website. Downloads kommen von GitHub Releases.",
				],
			},
			{
				heading: "Deine Rechte",
				level: 2,
				paragraphs: [
					`Nach der DSGVO und ähnlichen Gesetzen kannst du Auskunft verlangen, Berichtigung oder Löschung fordern, der Verarbeitung widersprechen und deine Einwilligung so einfach widerrufen, wie du sie erteilt hast. Der Widerruf ist der oben beschriebene Link im Fußbereich und wirkt sofort. Bei der Warteliste ist die Löschung die ganze Geschichte — deine E-Mail-Adresse ist das einzige personenbezogene Datum, das wir halten. Schreib an ${MAILTO} oder eröffne ein Issue auf ${GITHUB}.`,
				],
			},
			{
				heading: "Änderungen",
				level: 2,
				paragraphs: [
					`Ändert sich diese Erklärung, ändert sich das Datum oben mit, und die Historie ist öffentlich im ${repo("Quell-Repository")} der Website.`,
				],
			},
		],
	},
	fr: {
		title: "Politique de confidentialité",
		description: "Ce que ce site conserve, à partir de quand, et comment changer d'avis.",
		eyebrow: "Mentions légales",
		manageCta: "Modifier votre réponse",
		intro: `Brainstorm est un produit local-first, et ce site suit la même ligne : collecter le moins possible, garder ce qui est collecté ennuyeux, demander avant de conserver quoi que ce soit, et ne jamais monnayer votre attention ni vos données. Cette page décrit tout ce que le site ${SITE_LINK} fait avec des données. L'application Brainstorm, elle, garde vos données sur votre machine et n'a aucun système de compte ; rien ici ne concerne l'application.`,
		blocks: [
			{ heading: "Ce que nous collectons", level: 2, paragraphs: [] },
			{
				heading: "Mesure d'audience — seulement si vous acceptez",
				level: 3,
				manage: true,
				paragraphs: [
					"Nous aimerions compter les visites et voir quelles pages sont lues. Nous utilisons Amplitude pour cela, sur ses serveurs situés dans l'UE, et il ne fonctionne que si vous répondez oui à la question en bas de page. Jusque-là, le code de mesure n'est jamais téléchargé, ne s'exécute jamais et n'écrit rien sur votre appareil — c'est un consentement préalable, pas un interrupteur sur quelque chose de déjà chargé.",
					"Si vous acceptez, deux choses sont conservées sur votre appareil, dans <code>localStorage</code> et non dans des cookies. D'abord un identifiant d'appareil et de session aléatoire produit par Amplitude : il identifie un navigateur, pas une personne, et n'est jamais rapproché d'un nom ou d'une adresse e-mail. Ensuite notre propre trace de votre réponse — le mot « granted » ou « denied » et sa date — sous la clé <code>bs-consent</code>. Si vous refusez, seule la seconde est conservée, pour que nous sachions ne plus vous demander.",
					"Ce qui est envoyé tant que c'est actif : la page consultée, son titre et son référent, la langue et la taille d'écran de votre navigateur, et des événements nommés pour ce qui mérite d'être compté — un clic de téléchargement (quelle plateforme, quelle version) et une inscription à la liste ou à la newsletter. Amplitude déduit un pays approximatif de votre adresse IP. Nous n'envoyons jamais votre adresse e-mail, votre nom, ni ce que vous saisissez dans un champ.",
					"La base légale est votre consentement, au titre de l'art. 6(1)(a) du RGPD et des règles ePrivacy qui encadrent tout stockage sur votre appareil. Amplitude Inc. agit comme sous-traitant dans le cadre d'un accord de traitement, les données restant dans l'UE. Les événements sont conservés 12 mois puis supprimés. Votre réponse est mémorisée 12 mois, après quoi nous redemandons.",
					"Vous pouvez changer d'avis à tout moment — le lien « Options de suivi » en pied de chaque page rouvre la question. Y répondre non arrête la mesure immédiatement et supprime l'identifiant conservé dans votre navigateur.",
					"Si votre navigateur envoie un signal Global Privacy Control ou Do Not Track, nous le prenons pour un non : la question n'est pas posée, rien n'est chargé et rien n'est conservé.",
				],
			},
			{
				heading: "Votre adresse e-mail, si vous nous la donnez",
				level: 3,
				paragraphs: [
					`Si vous rejoignez la liste d'attente ou vous abonnez aux nouveautés, nous conservons l'adresse e-mail transmise dans une base de données (hébergée par Turso) et l'utilisons pour une seule chose : vous envoyer les nouveautés de Brainstorm. Nous ne la partageons pas, ne la vendons pas et ne l'enrichissons pas. Pour la faire retirer, écrivez à ${MAILTO} et nous la supprimerons.`,
				],
			},
			{
				heading: "Une préférence de thème",
				level: 3,
				paragraphs: [
					"Si vous passez du thème clair au thème sombre, le choix est conservé dans un cookie <code>bs-theme</code> pour que le site et la documentation s'ouvrent dans le thème retenu. Il contient le mot « light » ou « dark », rien d'autre. Il est fonctionnel, pas de mesure d'audience, et il est posé indépendamment de votre réponse sur le suivi.",
				],
			},
			{
				heading: "Journaux serveur",
				level: 3,
				paragraphs: [
					"Le site est hébergé par Vercel, qui conserve des journaux de requêtes standard et de courte durée (adresse IP, agent utilisateur) pour l'exploitation et la lutte contre les abus, en qualité de sous-traitant.",
				],
			},
			{
				heading: "Ce qui est chargé depuis des tiers",
				level: 2,
				paragraphs: [
					"La vidéo de présentation est intégrée depuis <code>youtube-nocookie.com</code> et ne se charge qu'après un clic sur lecture ; avant cela, aucune requête ne part vers YouTube. Le pied de page affiche les badges des annuaires de lancement où nous sommes référencés (VerifiedDR, Endors, KittyLaunch, ListBulb, Product Watch, StartupBase) — charger ces images envoie les données de requête habituelles (adresse IP, agent utilisateur) à ces hôtes, comme toute image sur le web. À part Amplitude, et seulement après votre accord, aucun script tiers ne s'exécute sur ce site. Les téléchargements sont servis par GitHub Releases.",
				],
			},
			{
				heading: "Vos droits",
				level: 2,
				paragraphs: [
					`Au titre du RGPD et de lois similaires, vous pouvez demander ce que nous détenons à votre sujet, en demander la correction ou la suppression, vous opposer au traitement, et retirer votre consentement aussi facilement que vous l'avez donné. Le retrait, c'est le lien de pied de page décrit plus haut, et il prend effet immédiatement. Pour la liste d'attente, la suppression résume tout — votre adresse e-mail est la seule donnée personnelle que nous détenons. Écrivez à ${MAILTO} ou ouvrez une issue sur ${GITHUB}.`,
				],
			},
			{
				heading: "Modifications",
				level: 2,
				paragraphs: [
					`Si cette politique change, la date ci-dessus change avec elle, et l'historique est public dans le ${repo("dépôt source")} du site.`,
				],
			},
		],
	},
};

export function privacyCopy(lang: Lang): PrivacyCopy {
	return privacy[lang];
}
